apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-env
  namespace: laravel
data:
  .env: |
    APP_NAME=Laravel
    APP_ENV=local
    APP_KEY=base64:76CnBEITJSepypgVBsxPbflw1OELKkuGKMmnk3EI7co=
    APP_DEBUG=true
    APP_URL=http://localhost:8000

    LOG_CHANNEL=stack

    DB_CONNECTION=mysql
    DB_HOST=mysql-service
    DB_PORT=3306
    DB_DATABASE=laravel_starter
    DB_USERNAME=laravel_user
    DB_PASSWORD=vishuanshi

    BROADCAST_DRIVER=log
    CACHE_DRIVER=file
    QUEUE_CONNECTION=sync
    SESSION_DRIVER=file
    SESSION_LIFETIME=120
