apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-deployment
  namespace: laravel
  labels:
    app: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: laravel
          image: vishal2728/devopslaravel:23
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: laravel-service
  namespace: laravel
spec:
  type: NodePort
  selector:
    app: laravel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
